# Generated by Django 4.2.6 on 2023-10-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0002_post_title_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title_tag",
            field=models.CharField(max_length=255),
        ),
    ]
